'use strict';

const fs = require('fs');
const path = require('path');
const AdmZip = require('adm-zip');
const { resolveProjectPath } = require('../context');
const { MANIFEST_FILE, canonicalZipPayloadSha256 } = require('../release-integrity');

async function run(context) {
    const config = context.config.zip || {};
    if (config.enabled === false) {
        return { skipped: true };
    }
    if (!fs.existsSync(context.buildRoot)) {
        throw new Error(`Build root not found: ${context.buildRoot}`);
    }
    if (!context.fingerprintAudit || context.fingerprintAudit.passed !== true) {
        throw new Error('zipBuild requires a successful fingerprintBuild audit in the same pipeline run');
    }
    const manifestPath = path.join(context.buildRoot, MANIFEST_FILE);
    if (!fs.existsSync(manifestPath)) {
        throw new Error(`zipBuild requires ${MANIFEST_FILE} generated by fingerprintBuild`);
    }

    const outputTemplate = config.output || 'project://build/{outputName}.zip';
    const output = resolveProjectPath(
        context.projectRoot,
        outputTemplate.replace(/\{platform\}/g, context.platform).replace(/\{outputName\}/g, context.outputName)
    );

    let zipSha256 = '';
    if (!context.dryRun) {
        fs.mkdirSync(path.dirname(output), { recursive: true });
        const rootInZip = config.root || context.outputName;
        writeBuildZip(context.buildRoot, rootInZip, output);
        const finalZip = new AdmZip(output);
        zipSha256 = canonicalZipPayloadSha256(finalZip);
        updateManifestZipDigest(manifestPath, zipSha256);
        if (context.integrityManifest) context.integrityManifest.zipSha256 = zipSha256;
        const fingerprintTask = (context.report.tasks || []).find((task) => task.name === 'fingerprintBuild' && task.result);
        if (fingerprintTask && fingerprintTask.result.integrityManifest) {
            fingerprintTask.result.integrityManifest.zipSha256 = zipSha256;
        }
        writeBuildZip(context.buildRoot, config.root || context.outputName, output);
        const verifiedZip = new AdmZip(output);
        const verifiedDigest = canonicalZipPayloadSha256(verifiedZip);
        if (verifiedDigest !== zipSha256) {
            throw new Error(`ZIP payload digest changed after manifest update: ${zipSha256} -> ${verifiedDigest}`);
        }
    } else if (fs.existsSync(output)) {
        zipSha256 = canonicalZipPayloadSha256(new AdmZip(output));
    }

    return {
        output,
        root: config.root || context.outputName,
        bytes: fs.existsSync(output) ? fs.statSync(output).size : 0,
        zipSha256,
    };
}

function writeBuildZip(buildRoot, rootInZip, output) {
    const zip = new AdmZip();
    zip.addLocalFolder(buildRoot, rootInZip);
    writeZipAtomically(zip, output);
}

function updateManifestZipDigest(manifestPath, zipSha256) {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    manifest.zipSha256 = zipSha256;
    const temporary = `${manifestPath}.release-pipeline-${process.pid}-${Date.now()}.tmp`;
    try {
        fs.writeFileSync(temporary, JSON.stringify(manifest, null, 2), 'utf8');
        fs.renameSync(temporary, manifestPath);
    } catch (error) {
        if (fs.existsSync(temporary)) fs.rmSync(temporary, { force: true });
        throw new Error(`Cannot update ${MANIFEST_FILE}: ${error.message}`);
    }
}

function writeZipAtomically(zip, output) {
    const temporary = `${output}.release-pipeline-${process.pid}-${Date.now()}.tmp`;
    const previous = `${output}.release-pipeline-previous-${process.pid}-${Date.now()}.tmp`;
    let movedPrevious = false;
    try {
        zip.writeZip(temporary);
        if (fs.existsSync(output)) {
            fs.renameSync(output, previous);
            movedPrevious = true;
        }
        fs.renameSync(temporary, output);
        if (movedPrevious) {
            fs.rmSync(previous, { force: true });
        }
    } catch (error) {
        if (fs.existsSync(temporary)) fs.rmSync(temporary, { force: true });
        if (movedPrevious && !fs.existsSync(output) && fs.existsSync(previous)) {
            fs.renameSync(previous, output);
        }
        throw new Error(`Cannot atomically write zip: ${error.message}`);
    }
}

module.exports = { run };
